package com.bidostar.dblibrary.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.bidostar.dblibrary.bean.CarBean;
import com.bidostar.dblibrary.bean.UserBean;

import com.bidostar.dblibrary.db.CarBeanDao;
import com.bidostar.dblibrary.db.UserBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig carBeanDaoConfig;
    private final DaoConfig userBeanDaoConfig;

    private final CarBeanDao carBeanDao;
    private final UserBeanDao userBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        carBeanDaoConfig = daoConfigMap.get(CarBeanDao.class).clone();
        carBeanDaoConfig.initIdentityScope(type);

        userBeanDaoConfig = daoConfigMap.get(UserBeanDao.class).clone();
        userBeanDaoConfig.initIdentityScope(type);

        carBeanDao = new CarBeanDao(carBeanDaoConfig, this);
        userBeanDao = new UserBeanDao(userBeanDaoConfig, this);

        registerDao(CarBean.class, carBeanDao);
        registerDao(UserBean.class, userBeanDao);
    }
    
    public void clear() {
        carBeanDaoConfig.clearIdentityScope();
        userBeanDaoConfig.clearIdentityScope();
    }

    public CarBeanDao getCarBeanDao() {
        return carBeanDao;
    }

    public UserBeanDao getUserBeanDao() {
        return userBeanDao;
    }

}
